In [212]:
import pandas as pd

In [214]:
import numpy as np

In [216]:
import warnings

In [218]:
warnings.filterwarnings("ignore")

### загрузка таблицы "Wine.csv" c github

In [221]:
df = pd.read_csv (r"https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Wine.csv")

In [222]:
df

,class_label,class_name,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280,proline
0,1,Barolo,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,Barolo,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,Barolo,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,Barolo,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,Barolo,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,Barbera,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,Barbera,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,Barbera,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,Barbera,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,Barbera,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

### Написать функцию и применить ее к данным с помощью apply()

In [224]:
# функция переводит показатель пролина из мг/дм3 в г/литр 
convector = lambda x: x/1000
# результат записываем в новый столбец proline_g/liter
df['proline_g/liter'] = df['proline'].apply(convector)

In [226]:
df

,class_label,class_name,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280,proline,proline_g/liter
0,1,Barolo,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1.065
1,1,Barolo,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1.050
2,1,Barolo,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1.185
3,1,Barolo,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1.480
4,1,Barolo,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,Barbera,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,0.740
174,3,Barbera,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,0.750
175,3,Barbera,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,0.835
176,3,Barbera,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,0.840
177,3,Barbera,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,0.560

### Напишите функцию и примените её к данным с помощью .transform

In [231]:
# функция считает на сколько процентов одно число больше другого
# функция = (Число1/Число2) · 100 − 100
def get_proline_percent(df):
     return round((df.mean()/df)*100-100,2)

In [239]:
# записываем процент по модулю в столбец proline_percent.
# proline_percent показывает на сколько процентов proline отличается от среднего значения в процентах.
# Если процент положительный (среднее proline < proline) то делаем вывод Контрафакт.
# То есть на процент (proline_percent) данное вино возможно будет Контрафактом.
# Если процент отрицательный (среднее proline > proline) то делаем вывод Норма.
# То есть на процент (proline_percent) данное вино возможно будет Нормальным.
# Вывод: в приставленной таблицы вин по показателю proline возможны контрофактные партии.
df['proline_percent'] = abs(df.groupby('class_name')['proline'].transform(get_proline_percent))
df['proline_result'] = np.where (df.groupby('class_name')['proline'].transform(get_proline_percent) >0, 'Контрафакт', 'Норма')
df

,class_label,class_name,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280,proline,proline_g/liter,proline_percent,proline_result
0,1,Barolo,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1.065,4.76,Контрафакт
1,1,Barolo,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1.050,6.26,Контрафакт
2,1,Barolo,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1.185,5.85,Норма
3,1,Barolo,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1.480,24.61,Норма
4,1,Barolo,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.735,51.80,Контрафакт
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,Barbera,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,0.740,14.88,Норма
174,3,Barbera,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,0.750,16.01,Норма
175,3,Barbera,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,0.835,24.56,Норма
176,3,Barbera,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,0.840,25.01,Норма
177,3,Barbera,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,0.560,12.48,Контрафакт

### Напишите функцию и примените её к данным с помощью .map

In [242]:
# функция добавляет к переменной символ %
df['proline_percent'] = df['proline_percent'].map(lambda x: str(x) + '%')

In [244]:
df

,class_label,class_name,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280,proline,proline_g/liter,proline_percent,proline_result
0,1,Barolo,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1.065,4.76%,Контрафакт
1,1,Barolo,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1.050,6.26%,Контрафакт
2,1,Barolo,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1.185,5.85%,Норма
3,1,Barolo,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1.480,24.61%,Норма
4,1,Barolo,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.735,51.8%,Контрафакт
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,Barbera,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,0.740,14.88%,Норма
174,3,Barbera,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,0.750,16.01%,Норма
175,3,Barbera,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,0.835,24.56%,Норма
176,3,Barbera,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,0.840,25.01%,Норма
177,3,Barbera,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,0.560,12.48%,Контрафакт

### Группировать данные по дате и использовать resample для агрегирования в более крупный период.

In [247]:
# генерирую список дат и записываю их в столбец для отдельных class_name, чтобы даты повторялись
df.insert((df.columns.get_loc('class_name')+1),'date',0)
index = 0
idate = 0
values = df['class_name'].unique()
date = pd.date_range('2016-01-15','2024-09-24', periods = 71 ).date
for value in values:
    idate=0
    while value == df.loc[index,'class_name']:
        df.loc[index,'date'] = date[idate]
        index=index+1
        if index==df['class_name'].shape[0]:
            break
        idate=idate+1
# переводим формат из object в datetime64
df['date']= pd.to_datetime(df['date'])

In [249]:
#группируем по дате и агрегируем среднее значение alcohol
df_date = df.groupby('date').agg({'alcohol':'mean'})
df_date

              alcohol
date
2016-01-15  13.153333
2016-02-29  12.803333
2016-04-14  12.870000
2016-05-30  13.580000
2016-07-14  12.706667
...               ...
2024-03-26  12.070000
2024-05-10  12.430000
2024-06-25  11.790000
2024-08-09  12.370000
2024-09-24  12.040000

[71 rows x 1 columns]

In [251]:
# Средне значение alcohol в вине по годам.
# Вывод: современная тенденция уменьшать процент alcohol в вине
df_date.resample('YS').mean()

              alcohol
date
2016-01-01  13.042500
2017-01-01  13.379167
2018-01-01  13.068750
2019-01-01  12.980000
2020-01-01  13.006667
2021-01-01  13.147407
2022-01-01  12.751250
2023-01-01  12.359375
2024-01-01  12.095000